### PR TITLE
Filter Debezium schema change events. Fixes #90

### LINKED ISSUE #90: BatchConsumer throws NPE for MSSQL
```java
2023-02-16 15:24:22,454 INFO  [io.deb.con.sql.SqlServerChangeEventSourceCoordinator] (debezium-sqlserverconnector-e2e-rule-10.244.0.92-change-event-source-coordinator) Starting streaming
2023-02-16 15:24:22,454 INFO  [io.deb.con.sql.SqlServerStreamingChangeEventSource] (debezium-sqlserverconnector-e2e-rule-10.244.0.92-change-event-source-coordinator) Last position recorded in offsets is 00000025:00000418:0001(NULL)[1]
2023-02-16 15:24:22,918 INFO  [io.gin.cdc.con.BatchConsumer] (engine) Processing 2 entries
2023-02-16 15:24:22,918 INFO  [io.gin.cdc.cha.CacheBackendLink] (engine) BEFORE -> null
2023-02-16 15:24:22,918 INFO  [io.gin.cdc.cha.CacheBackendLink] (engine) BEFORE -> null
2023-02-16 15:24:22,918 INFO  [io.gin.cdc.cha.CacheBackendLink] (engine) AFTER -> null
2023-02-16 15:24:22,918 INFO  [io.gin.cdc.cha.CacheBackendLink] (engine) AFTER -> {"id":1,"email":"alice@example.com","fullname":"Alice"}
2023-02-16 15:24:22,919 INFO  [io.gin.cdc.con.BatchConsumer] (engine) Exception encountered writing updates for engine e2e-rule: java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "org.infinispan.commons.dataconversion.internal.Json.asString()" because the return value of "org.infinispan.commons.dataconversion.internal.Json.at(String)" is null
	at io.gingersnapproject.cdc.util.CompletionStages.join(CompletionStages.java:86)
	at io.gingersnapproject.cdc.consumer.BatchConsumer.handleBatch(BatchConsumer.java:54)
	at io.debezium.embedded.ConvertingEngineBuilder.lambda$notifying$2(ConvertingEngineBuilder.java:86)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:881)
	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:195)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "org.infinispan.commons.dataconversion.internal.Json.asString()" because the return value of "org.infinispan.commons.dataconversion.internal.Json.at(String)" is null
	at io.gingersnapproject.cdc.chain.CacheBackendLink.processAsync(CacheBackendLink.java:39)
	at io.gingersnapproject.cdc.chain.CacheBackendLink.process(CacheBackendLink.java:28)
	at io.gingersnapproject.cdc.chain.EventProcessingChain.processNext(EventProcessingChain.java:23)
	at io.gingersnapproject.cdc.chain.EventFilterLink.process(EventFilterLink.java:37)
	at io.gingersnapproject.cdc.consumer.BatchConsumer.lambda$handleBatch$1(BatchConsumer.java:59)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 3 more

```

Debezium Event JSON:

```json
{
	"source": {
		"version": "2.0.0.Final",
		"connector": "sqlserver",
		"name": "e2e-rule-10.244.0.101",
		"ts_ms": 1676561650277,
		"snapshot": "true",
		"db": "gingersnap",
		"schema": "gingersnap",
		"table": "customer",
		"commit_lsn": "00000025:00000410:0003"
	},
	"ts_ms": 1676561650277,
	"databaseName": "gingersnap",
	"schemaName": "gingersnap",
	"tableChanges": [{
		"type": "CREATE",
		"id": "\"gingersnap\".\"gingersnap\".\"customer\"",
		"table": {
			"primaryKeyColumnNames": ["id"],
			"columns": [{
				"name": "id",
				"jdbcType": -5,
				"typeName": "bigint",
				"typeExpression": "bigint",
				"length": 19,
				"scale": 0,
				"position": 1,
				"optional": false,
				"autoIncremented": false,
				"generated": false
			}, {
				"name": "email",
				"jdbcType": 12,
				"typeName": "varchar",
				"typeExpression": "varchar",
				"length": 255,
				"position": 2,
				"optional": true,
				"autoIncremented": false,
				"generated": false
			}, {
				"name": "fullname",
				"jdbcType": 12,
				"typeName": "varchar",
				"typeExpression": "varchar",
				"length": 255,
				"position": 3,
				"optional": true,
				"autoIncremented": false,
				"generated": false
			}]
		}
	}]
}
```

### PR DESCRIPTION
**Pull request by ryanemerson**

### CODE REVIEW

File: src/main/java/io/gingersnapproject/cdc/chain/EventFilterLink.java [hunk 1]
```diff
@@ -6,6 +6,8 @@
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
 
+import java.util.function.Function;
```
Comment (jabolina) [inline src/main/java/io/gingersnapproject/cdc/chain/EventFilterLink.java:9]: Unused.

**Review by jabolina — APPROVED** [review]

**Comment by jabolina** [comment]
Merged, thanks @ryanemerson
